### ISSUE TITLE
Non-consumable items seem to be consumed automatically and are therefore also not available to Restore

### ISSUE THREAD

**Issue by diesel-dogg** [solar2d/com.solar2d-plugin.google.iap.billing.v2#3]
The v2 plugin appears to behave differently to the original plugin wherein it doesn't account for purchases that are not explicitly consumed. This makes it impossible to handle non-consumable items for Google Play deployment.

Simply- When handling the PURCHASE state callback for non-consumables, not calling the consume function appears to make no difference as items are consumed regardless

To make a purchase, the functoin below is called:

```
function IAP.purchase(productIdentifier)
	if (checkProhibitedApp())then
		toast.showToast(textResource.prohibitedAppText)
		--fire an event if a prohibited app was found
		analytics.sendTrackingEvent("BlockedProhibitedApp")
		return
	end
        --Call the purchase function for the plugin. "STORE" is the instance of the plugin
	store.purchase(productIdentifier)
end
```

Below is the transactionListener. Of importance here is the call to a third function called performProductAction when a PURCHASED state callback is received.

```
function transactionListenerAndroid(event)

   local transaction = event.transaction

   -- Google IAP initialization event
    if ( event.name == "init" ) then
        if not ( transaction.isError ) then
            -- Perform steps to enable IAP, load products, etc.
 			if(store.canLoadProducts)then
 				--populate a local table of just product IDs and call the loadProducts function
 				local ids={}
 				for i=1,#productIdentifiers do
 					ids[#ids+1]=productIdentifiers[i].id
 				end
 				store.loadProducts(ids,productListener)
 			end	
        else  -- Unsuccessful initialization; output error details
            debugStmt.print("IAP:"..transaction.errorType)
            debugStmt.print("IAP:"..transaction.errorString)
        end

    -- Store transaction event
    elseif ( event.name == "storeTransaction" ) then
        if not ( transaction.state == "failed" ) then  -- Successful transaction
 			if ( transaction.state == "purchased") then
 				toast.showToast("IAP: puchased "..transaction.productIdentifier)
	            -- Handle a normal purchase or restored purchase here
	            performProductAction(transaction.productIdentifier)
	            store.finishTransaction( transaction )--this will end the transaction, if not called the transaction will remain incomplete and continue on next app launch
	        elseif(transaction.state=="consumed")then
	        	
	        elseif(transaction.state=="refunded")then
	        
	        elseif ( transaction.state == "cancelled" ) then
	            -- Handle a cancelled transaction here
	 			debugStmt.print("IAP:"..transaction.state)
	        end
        else  -- Unsuccessful transaction; output error details
			
			-- if transaction fails with error 7 it means user has already owned the product. In case if the product is non-consumeable it is fine. But we need to make the consumable product to be purchaseable again.
			-- to do this we need to consume all the consumable products. This will make them purchaseable again.
			if (transaction.errorType == 7) then
				--consume all consumable products because sometimes they become non-consumable if an error occured and the product was failed to be consumed.
				--We will iterate over all porducts from the product identifier table and consume all the products based on their ID which have a TRUE flage for their consumable status
 				for i=1,#productIdentifiers do
 					if(productIdentifiers[i].isConsumable)then
 						store.consumePurchase(productIdentifiers[i].id)
 					end
 				end
			end

			toast.showToast("IAP: error "..transaction.errorType)
			toast.showToast("IAP: error "..transaction.errorString)

            debugStmt.print("IAP failed type:"..transaction.errorType )
            debugStmt.print("IAP failed string:"..transaction.errorString )
        end
    end
end
```

The function below is called from the listener above. This is where I check for the type of product (consumable or non) and then perform app-specific actions as well as consume the product if required. You'd notice that consume is not called on items like "noads" etc but they are still somehow available to purchase after a few seconds.

```
function performProductAction(identifier)
	if(identifier=="com.famousdoggstudios.pg.noads")then
		analytics.sendTrackingEvent("noAdsPurchased")
		toast.showToast(textResource.pleaseRestart)
		preferenceHandler.set("isNoAdsPurchased",true)
	elseif(identifier=="com.famousdoggstudios.pg.currency1" and not isPurchaseRestoreInProgress)then--this item will not be purchasable during the restoration process. This is due to an issue with Google Billing plugin. see top of script where the variable is defined for details. 
		if(targetAppStore=="google")then--only required for android
			-- timer to wait sometime after the purchase call before consuming the product
			timerService.addTimer(100, function() store.consumePurchase(identifier)  
											debugStmt.print("IAP: consumed currency1")
										end, nil, true) -- exempt from service so that timer doesn't get paused.

   		end
		analytics.sendTrackingEvent("currency1Purchased")
		toast.showToast(textResource.purchaseGreeting)
		preferenceHandler.set("currency",preferenceHandler.get("currency")+4000)
	elseif(identifier=="com.famousdoggstudios.pg.currency2" and not isPurchaseRestoreInProgress)then--this item will not be purchasable during the restoration process.
		if(targetAppStore=="google")then--only required for android
			-- timer to wait sometime after the purchase call before consuming the product
			timerService.addTimer(100, function() store.consumePurchase(identifier)  
										debugStmt.print("IAP: consumed currency2")
									end, nil, true) -- exempt from service so that timer doesn't get paused.

		end
		analytics.sendTrackingEvent("currency2Purchased")
		toast.showToast(textResource.purchaseGreeting)
		preferenceHandler.set("currency",preferenceHandler.get("currency")+9000)	
	elseif(identifier=="com.famousdoggstudios.pg.noadshalf")then
		analytics.sendTrackingEvent("noAdsHalfPurchased")
		toast.showToast(textResource.pleaseRestart)
		preferenceHandler.set("isNoAdsPurchased",true)
   	end
end
```

**Comment by diesel-dogg** [comment]
Notes based on further testing:

- If an item is not consumed explicitly in the code and restore is called, the purchased item is restored correctly
- If an attempt is made to purchase this item another time, an error message is displayed indicating that the item was owned
- This is where the problem is-- after the above error message, transaction events go through on this item where it is automatically consumed and a Consumed state callback is also received. This happens with no explicit call being made for the consume operation in the code.
- Subsequently, the item is again available for purchase since it was consumed. 

I'm sure you'd be able to reproduce this behaviour. Hopefully it can be looked into. Completely changing a Shop UI to exclude an item that was a non-consumable to work around this problem is a last resort but I'm hopeful this can be fixed.

**Comment by scottrules44** [comment]
> for i=1,#productIdentifiers do
>  					if(productIdentifiers[i].isConsumable)then
>  						store.consumePurchase(productIdentifiers[i].id)
>  					end
>  				end

Is the ".isConsumable" handled properly? I not getting an automatic "consumed" state after trying to repurchase a non consumable and getting that error message.

**Comment by diesel-dogg** [comment]
It does appear to be work as intended because I had printed the identifiers of the products inside the IF clause and it is only the consumable products like I'd expect. 

This bit of code was mainly a safeguard for the V1 plugin where some items did not consume successfully so by having this code in there, it was possible to attempt consuming them at a later stage. 

Since you are unable to reproduce this behaviour, I am beginning to think that the consume function is working differently in V2. Possibly, it is not respecting the product identifier at all and just consuming the item last recorded in transaction? I'll rework the code to start using the actual transaction in my Consume calls instead of the product identifier and see if that works.

**Comment by Shchvova** [comment]
As far as I remember originally google IAP plugin didn't distinguish between consumable and non consumable purchases. Difference was on client code. You couldn't just buy item twice. You had to consume it if you want to be able to buy another. Thus you could use item as a flag, or consume it when purchased, up to developer.

**Comment by diesel-dogg** [comment]
> As far as I remember originally google IAP plugin didn't distinguish between consumable and non consumable purchases. Difference was on client code. You couldn't just buy item twice. You had to consume it if you want to be able to buy another. Thus you could use item as a flag, or consume it when purchased, up to developer.

Precisely. Although, I reckon you may have misunderstood the issue that I was facing. So, I was actually using identifiers and an "isConsumable" flag in my own code to help distinguish the two types of items and then consume only the consumable ones, just like you have suggested. The problem, however, is that in the V2 plugin, there seems to be something going on where the consumePurchase function is not behaving as expected and is consuming items BESIDES the one that I specify in the function's argument. Now testing further based on Scott's last post and will report back.

**Comment by scottrules44** [comment]
@diesel-dogg I was reproduce issue, 1. Purchase non consumable, 2. Consume a different product id then step 1  3.  Product in step 1 is available for repurchase

**Comment by diesel-dogg** [comment]
@scottrules44 So the second step of consuming a different product ID would mean that if another product is purchased and consumed after previously having purchased a non-consumable, the non-consumable will again become available?

Is this a plugin issue or something with the Android library itself you reckon?

**Comment by scottrules44** [comment]
@diesel-dogg I just found and fixed what I believe to be the bug. Basically, the code was ignoring params passed in .consumePurchase() and consuming(essential resetting) everything when called. I just put an update that should fix this issue
