### ISSUE TITLE
subscriptions not acknowledged

### ISSUE THREAD

**Issue by tomaz42** [solar2d/com.solar2d-plugin.google.iap.billing.v2#5]
I believe there is a bug in V2 plugin, regarding acknowledging subscriptions.
After calling finishTransaction on subscription, subscription is not acknowledged and is refunded to user.

I believe problem is in:
private int finishTransaction(LuaState L) {
…
getPurchasesFromTransaction(L, true, processPurchases); // this is called in IAPsOnly mode (2nd param)
…
}

best regards,
Tom

**Comment by KevBradford** [comment]
We are seeing the same behavior with the new V2 plugin, subscriptions are not being acknowledged.

**Comment by scottrules44** [comment]
This should be fixed
